In [1]:
import cv2
import random

In [2]:
img = cv2.imread('Assets/dog_image.jpg', -1)

In [3]:
# image is represented in form of matrix
print(img)

[[[  5 116  96]
  [  5 116  96]
  [  6 114  95]
  ...
  [ 23  79  96]
  [ 23  79  96]
  [ 23  79  96]]

 [[  5 116  94]
  [  5 116  94]
  [  7 116  94]
  ...
  [ 24  80  97]
  [ 24  80  97]
  [ 24  80  97]]

 [[  5 117  93]
  [  5 117  93]
  [  7 117  93]
  ...
  [ 26  82 101]
  [ 26  82 101]
  [ 26  82 101]]

 ...

 [[  0  88  60]
  [  0  80  66]
  [ 44 130 130]
  ...
  [ 33 132 114]
  [  4  94  75]
  [  0  68  50]]

 [[  0  82  57]
  [  1  84  75]
  [ 44 116 123]
  ...
  [ 40 144 127]
  [  1  84  69]
  [ 17  79  65]]

 [[  9  95  71]
  [ 41 113 107]
  [ 76 132 143]
  ...
  [  6 108  96]
  [  0  46  34]
  [ 27  71  58]]]


In [4]:
print(type(img))

<class 'numpy.ndarray'>


In [5]:
print(img.shape)

(408, 612, 3)


Accessing Pixel Values

In [6]:
# first row of our image(Height)
print(img[0])

[[  5 116  96]
 [  5 116  96]
 [  6 114  95]
 ...
 [ 23  79  96]
 [ 23  79  96]
 [ 23  79  96]]


In [7]:
# both rows and columns(Height & width)
print(img[30][79])

[ 41 165 153]


In [8]:
# a single pixel
print(img[30][79:90])

[[ 41 165 153]
 [ 39 167 155]
 [ 39 167 155]
 [ 39 168 153]
 [ 40 169 154]
 [ 39 169 152]
 [ 38 169 149]
 [ 37 168 148]
 [ 36 167 146]
 [ 34 167 147]
 [ 34 167 147]]


Changing Pixel Colors

In [10]:
# changing the pixel color
for i in range(400):
    for j in range(img.shape[1]):
        img[i][j] = [random.randint(0,255), random.randint(0,255), random.randint(0,255)]

In [ ]:
# displaying the image
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

Copy and Pasting parts of the Image

In [42]:
# dimension of both the slice should be same
tag = img[400:700, 600:900]       # slice copied
img[100:400, 200:500] = tag       # slice pasted

In [43]:
cv2.imshow('Image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()